import jsPDF from "jspdf";

/**
 * Generate PDF for Parent Summary
 */
export interface ParentSummaryData {
  month: string;
  monthKey: string;
  totalSpending: number;
  totalExpenses: number;
  totalBills: number;
  categoryBreakdown: Array<{
    category: string;
    amount: number;
    percentage: number;
    expenses: number;
    bills: number;
  }>;
  topCategories: Array<{
    category: string;
    amount: number;
    percentage: number;
  }>;
  largestTransactions: Array<{
    id: string;
    type: "EXPENSE" | "BILL";
    description: string;
    amount: number;
    date: string;
    category: string;
    paidBy: string;
  }>;
}

export function generateParentSummaryPDF(data: ParentSummaryData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPos = margin;
    }
  };

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FlatFlow - Parent Summary", pageWidth / 2, yPos, { align: "center" });
  yPos += 10;

  // Month
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(data.month, pageWidth / 2, yPos, { align: "center" });
  yPos += 15;

  // Summary Stats
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", margin, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Total Spending: ₹${data.totalSpending.toLocaleString("en-IN")}`, margin, yPos);
  yPos += 6;
  doc.text(`Total Expenses: ₹${data.totalExpenses.toLocaleString("en-IN")}`, margin, yPos);
  yPos += 6;
  doc.text(`Total Bills: ₹${data.totalBills.toLocaleString("en-IN")}`, margin, yPos);
  yPos += 10;

  // Category Breakdown
  checkPageBreak(30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Category Breakdown", margin, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  data.categoryBreakdown.slice(0, 10).forEach((cat) => {
    checkPageBreak(6);
    const line = `${cat.category}: ₹${cat.amount.toLocaleString("en-IN")} (${cat.percentage.toFixed(1)}%)`;
    doc.text(line, margin, yPos);
    yPos += 6;
  });
  yPos += 5;

  // Top Categories
  checkPageBreak(30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Top Categories", margin, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  data.topCategories.slice(0, 5).forEach((cat) => {
    checkPageBreak(6);
    const line = `${cat.category}: ₹${cat.amount.toLocaleString("en-IN")} (${cat.percentage.toFixed(1)}%)`;
    doc.text(line, margin, yPos);
    yPos += 6;
  });
  yPos += 5;

  // Largest Transactions
  checkPageBreak(40);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Largest Transactions", margin, yPos);
  yPos += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  data.largestTransactions.slice(0, 10).forEach((txn) => {
    checkPageBreak(8);
    const date = new Date(txn.date).toLocaleDateString("en-IN", {
      day: "numeric",
      month: "short",
    });
    const line = `${txn.description} - ₹${txn.amount.toLocaleString("en-IN")} (${txn.category}) - ${date} - Paid by ${txn.paidBy}`;
    
    // Split long lines
    const maxWidth = pageWidth - 2 * margin;
    const lines = doc.splitTextToSize(line, maxWidth);
    lines.forEach((line: string) => {
      checkPageBreak(6);
      doc.text(line, margin, yPos);
      yPos += 6;
    });
    yPos += 2;
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text(
      `Generated by FlatFlow on ${new Date().toLocaleDateString("en-IN")} - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  // Save PDF
  const fileName = `flatflow-parent-summary-${data.monthKey.replace(/\s+/g, "-")}.pdf`;
  doc.save(fileName);
}

/**
 * Generate PDF for Balance Report
 */
export interface BalanceReportData {
  balances: Array<{
    memberId: string;
    memberName: string;
    owes: number;
    receives: number;
    netBalance: number;
  }>;
  generatedAt: string;
}

export function generateBalanceReportPDF(data: BalanceReportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = margin;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FlatFlow - Balance Report", pageWidth / 2, yPos, { align: "center" });
  yPos += 10;

  // Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Generated: ${new Date(data.generatedAt).toLocaleDateString("en-IN")}`,
    pageWidth / 2,
    yPos,
    { align: "center" }
  );
  yPos += 15;

  // Balance Table Header
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Member Balances", margin, yPos);
  yPos += 10;

  // Table Headers
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Member", margin, yPos);
  doc.text("Owes", margin + 60, yPos);
  doc.text("Receives", margin + 100, yPos);
  doc.text("Net Balance", margin + 150, yPos);
  yPos += 8;

  // Table Rows
  doc.setFont("helvetica", "normal");
  data.balances.forEach((balance) => {
    if (yPos > pageHeight - 30) {
      doc.addPage();
      yPos = margin;
    }

    doc.text(balance.memberName, margin, yPos);
    doc.text(`₹${balance.owes.toLocaleString("en-IN")}`, margin + 60, yPos);
    doc.text(`₹${balance.receives.toLocaleString("en-IN")}`, margin + 100, yPos);
    
    const netBalanceText = balance.netBalance > 0 
      ? `+₹${balance.netBalance.toLocaleString("en-IN")}`
      : `₹${balance.netBalance.toLocaleString("en-IN")}`;
    doc.text(netBalanceText, margin + 150, yPos);
    
    yPos += 7;
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text(
      `Generated by FlatFlow - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: "center" }
    );
  }

  // Save PDF
  const fileName = `flatflow-balance-report-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}

